# Generated by Django 5.2.17 on 2026-09-16 06:44

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('imports', '0001_initial'),
        ('searches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('spent_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('calls', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('make', models.CharField(db_index=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('generated', 'Generated'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('blocked', 'Budget blocked')], db_index=True, default='pending', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('seo_title', models.CharField(blank=True, default='', max_length=255)),
                ('seo_description', models.TextField(blank=True, default='')),
                ('seo_keywords', models.TextField(blank=True, default='')),
                ('ai_model', models.CharField(blank=True, default='', max_length=64)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('wp_post_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('wp_link', models.TextField(blank=True, null=True)),
                ('wp_status', models.CharField(blank=True, default='', max_length=32)),
                ('featured_media_id', models.PositiveIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('images_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='searches.carsearch')),
                ('csv_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='imports.csvimport')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('post_content', 'Blog post content')], default='post_content', max_length=32)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], db_index=True, default='reserved', max_length=16)),
                ('model', models.CharField(max_length=64)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('cached_prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('input_usd_per_1m', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('cached_input_usd_per_1m', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('output_usd_per_1m', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('reserved_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('finish_reason', models.CharField(blank=True, default='', max_length=32)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usages', to='publishing.blogpost')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_media_id', models.PositiveIntegerField(db_index=True)),
                ('wp_source_url', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('alt_text', models.TextField(blank=True, default='')),
                ('caption', models.TextField(blank=True, default='')),
                ('credit_url', models.TextField(blank=True, default='')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes_uploaded', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='publishing.blogpost')),
                ('car_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_media', to='images.carimage')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['make', 'model', 'year'], name='blog_posts_make_model_year_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', 'id'], name='blog_posts_status_id_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusage',
            index=models.Index(fields=['status', 'occurred_at'], name='ai_usage_status_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='blogpostmedia',
            constraint=models.UniqueConstraint(fields=('blog_post', 'car_image'), name='blog_post_media_post_image_unique'),
        ),
    ]
