# Generated by Django 5.2.17 on 2026-09-15 11:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('imports', '0001_initial'),
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('csv_upload', 'CSV upload'), ('csv_row', 'CSV row'), ('search_run', 'Search run'), ('image_download', 'Image download'), ('wikimedia_block', 'Wikimedia block')], max_length=32)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning')], default='error', max_length=16)),
                ('message', models.TextField(blank=True, null=True)),
                ('exception_class', models.CharField(blank=True, max_length=255, null=True)),
                ('exception_message', models.TextField(blank=True, null=True)),
                ('trace_excerpt', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('car_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_events', to='images.carimage')),
                ('car_search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_events', to='searches.carsearch')),
                ('csv_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_events', to='imports.csvimport')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['context', 'occurred_at'], name='error_events_context_time_idx')],
            },
        ),
    ]
