# Generated by Django 5.2.17 on 2026-09-16 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0001_initial'),
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorevent',
            name='blog_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_events', to='publishing.blogpost'),
        ),
        migrations.AlterField(
            model_name='errorevent',
            name='context',
            field=models.CharField(choices=[('csv_upload', 'CSV upload'), ('csv_row', 'CSV row'), ('search_run', 'Search run'), ('image_download', 'Image download'), ('wikimedia_block', 'Wikimedia block'), ('ai_generation', 'AI generation'), ('ai_budget', 'AI budget'), ('wordpress_publish', 'WordPress publish'), ('wordpress_media', 'WordPress media')], max_length=32),
        ),
    ]
