# Generated by Django 5.2.17 on 2026-09-15 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('searches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(db_index=True, max_length=255)),
                ('model', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('color', models.CharField(blank=True, max_length=64, null=True)),
                ('transparent_background', models.BooleanField(default=False)),
                ('provider', models.CharField(default='wikimedia', max_length=32)),
                ('provider_image_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('source_url', models.TextField()),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=255, null=True)),
                ('attribution', models.TextField(blank=True, null=True)),
                ('make_confirmed', models.BooleanField(blank=True, null=True)),
                ('year_confirmed', models.BooleanField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('download_status', models.CharField(choices=[('not_downloaded', 'Not downloaded'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('failed', 'Failed')], db_index=True, default='not_downloaded', max_length=32)),
                ('download_path', models.CharField(blank=True, max_length=512, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='searches.carsearch')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['make', 'model', 'year'], name='car_images_make_model_year_idx')],
                'constraints': [models.UniqueConstraint(fields=('car_search', 'year', 'provider', 'provider_image_id'), name='car_images_owner_provider_unique')],
            },
        ),
    ]
