# Generated by Django 5.2.17 on 2026-09-15 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('commons_category', models.CharField(blank=True, max_length=255, null=True)),
                ('from_year', models.PositiveSmallIntegerField()),
                ('to_year', models.PositiveSmallIntegerField()),
                ('color', models.CharField(blank=True, max_length=64, null=True)),
                ('transmission', models.CharField(blank=True, max_length=255, null=True)),
                ('transparent_background', models.BooleanField(default=False)),
                ('images_per_year', models.PositiveSmallIntegerField(default=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('csv_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='imports.csvimport')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'car search',
                'verbose_name_plural': 'car searches',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CommonsCategoryLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('make', 'model'), name='commons_category_lookups_make_model_unique')],
            },
        ),
        migrations.CreateModel(
            name='WikimediaBlockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.PositiveSmallIntegerField()),
                ('retry_after_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('response_excerpt', models.TextField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('car_search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_events', to='searches.carsearch')),
                ('csv_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_events', to='imports.csvimport')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
